# Generated by Django 4.2.6 on 2023-10-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_title",
                    models.CharField(max_length=125, verbose_name="Полное название"),
                ),
                (
                    "small_title",
                    models.CharField(
                        max_length=15, verbose_name="Сокращенное название"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата создания")),
            ],
            options={"verbose_name": "Универ", "verbose_name_plural": "Все универы",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="ФИО")),
                ("birthday", models.DateField(verbose_name="Дата рождения")),
                ("year", models.IntegerField(verbose_name="Год поступления")),
                (
                    "university",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nsu.university",
                    ),
                ),
            ],
            options={"verbose_name": "Студент", "verbose_name_plural": "Студенты",},
        ),
    ]
